/* Generated by po2c.py on 2026-02-07 04:33:28.886949 */
#ifndef LANGUAGES_H
#define LANGUAGES_H

#include <stdint.h>

// Global Language Setting
extern uint8_t sysLanguage; // 0=English, 1=German

// String Identifiers
enum StrID {
    S_WELCOME = 0,
    S_PRESS_CENTER = 1,
    S_SET_DATE = 2,
    S_SET_TIME = 3,
    S_TUTORIAL_TITLE = 4,
    S_TUT_1 = 5,
    S_TUT_2 = 6,
    S_TUT_3 = 7,
    S_MENU_ADMIN = 8,
    S_MENU_USER = 9,
    S_M_CHANGE_PASS = 10,
    S_M_CREATE_USER = 11,
    S_M_PERMS = 12,
    S_M_LANG = 13,
    S_M_LOGS = 14,
    S_M_ADVANCED = 15,
    S_M_EXIT = 16,
    S_DOOR_MENU = 17,
    S_OPEN_AS_G1 = 18,
    S_OPEN_AS_G2 = 19,
    S_OPEN_AS_ADMIN = 20,
    S_SETTINGS = 21,
    S_LOGIN_SETTINGS = 22,
    S_LOGIN_AS_G1 = 23,
    S_LOGIN_AS_G2 = 24,
    S_LOGIN_AS_ADMIN = 25,
    S_BACK = 26,
    S_DOOR_UNLOCKED = 27,
    S_INCORRECT_PASS = 28,
    S_PASS_SAVED = 29,
    S_MSG_NO_USERS = 30,
    S_MSG_USER_LIMIT_1 = 31,
    S_MSG_USER_LIMIT_2 = 32,
    S_MSG_USER_LIMIT_3 = 33,
    S_LOGS_TITLE = 34,
    S_LOGS_NONE = 35,
    S_LANG_SELECT = 36,
    S_M_LOGIN_SESSIONS = 37,
    S_CONF_TITLE = 38,
    S_LBL_ACTIVE = 39,
    S_LBL_CHG_PW = 40,
    S_ACC_TYPE = 41,
    S_LBL_COUNT = 42,
    S_ACC_PERM = 43,
    S_ACC_ONCE = 44,
    S_ACC_MULTI = 45,
    S_NEXT = 46,
    S_SAVE = 47,
    S_ACCESS_DENIED = 48,
    S_REMAINING = 49,
    S_M_LOGIN_U1 = 50,
    S_M_LOGIN_U2 = 51,
    S_COUNT
};

// String Table
extern const char* UI_STRINGS[2][S_COUNT];

// Helper Macro
#define GetStr(id) UI_STRINGS[sysLanguage][id]

#endif // LANGUAGES_H
