/* Generated by po2c.py on 2026-02-07 04:33:28.887316 */
#include "languages.h"

// --- DEFINITION OF GLOBAL VARIABLE ---
uint8_t sysLanguage = 0; // Default to English (0)

const char* UI_STRINGS[2][S_COUNT] = {
    { // English
        "Welcome!", // S_WELCOME
        "Press Center...", // S_PRESS_CENTER
        "Set Date:", // S_SET_DATE
        "Set Time:", // S_SET_TIME
        "Tutorial", // S_TUTORIAL_TITLE
        "In the next screen", // S_TUT_1
        "you draw a pattern", // S_TUT_2
        "as your password.", // S_TUT_3
        "ADMIN MENU", // S_MENU_ADMIN
        "USER MENU", // S_MENU_USER
        "Change Password", // S_M_CHANGE_PASS
        "Create new user", // S_M_CREATE_USER
        "Set Permissions", // S_M_PERMS
        "Language", // S_M_LANG
        "AdminLogs", // S_M_LOGS
        "Advanced", // S_M_ADVANCED
        "Exit", // S_M_EXIT
        "DOOR MENU", // S_DOOR_MENU
        "Open as Guest 1", // S_OPEN_AS_G1
        "Open as Guest 2", // S_OPEN_AS_G2
        "Open as Admin", // S_OPEN_AS_ADMIN
        "Settings", // S_SETTINGS
        "LOGIN SETTINGS", // S_LOGIN_SETTINGS
        "Login as Guest 1", // S_LOGIN_AS_G1
        "Login as Guest 2", // S_LOGIN_AS_G2
        "Login as Admin", // S_LOGIN_AS_ADMIN
        "Back", // S_BACK
        "Door Unlocked", // S_DOOR_UNLOCKED
        "Incorrect Password", // S_INCORRECT_PASS
        "Password Saved!", // S_PASS_SAVED
        "No users created", // S_MSG_NO_USERS
        "Creating more", // S_MSG_USER_LIMIT_1
        "users is not", // S_MSG_USER_LIMIT_2
        "allowed.", // S_MSG_USER_LIMIT_3
        "ADMIN LOGS", // S_LOGS_TITLE
        "No Logs Found", // S_LOGS_NONE
        "Select Language", // S_LANG_SELECT
        "Login Sessions", // S_M_LOGIN_SESSIONS
        "USER CONFIG", // S_CONF_TITLE
        "Active:", // S_LBL_ACTIVE
        "Chg PW:", // S_LBL_CHG_PW
        "Acc:", // S_ACC_TYPE
        "Cnt:", // S_LBL_COUNT
        "Perm", // S_ACC_PERM
        "1-Time", // S_ACC_ONCE
        "Multi", // S_ACC_MULTI
        "Next >", // S_NEXT
        "Save", // S_SAVE
        "Access Expired", // S_ACCESS_DENIED
        "Rem:", // S_REMAINING
        "Login as User 1", // S_M_LOGIN_U1
        "Login as User 2", // S_M_LOGIN_U2
    },
    { // German
        "Willkommen!", // S_WELCOME
        "Dr\200cken Sie Mitte", // S_PRESS_CENTER
        "Datum:", // S_SET_DATE
        "Uhrzeit:", // S_SET_TIME
        "Anleitung", // S_TUTORIAL_TITLE
        "Im n\176chsten Bild", // S_TUT_1
        "ein Muster als", // S_TUT_2
        "Passwort zeichnen.", // S_TUT_3
        "ADMIN MEN\175", // S_MENU_ADMIN
        "BENUTZER MEN\175", // S_MENU_USER
        "Passwort \176ndern", // S_M_CHANGE_PASS
        "Neuer Benutzer", // S_M_CREATE_USER
        "Berechtigungen", // S_M_PERMS
        "Sprache", // S_M_LANG
        "AdminLogs", // S_M_LOGS
        "Erweitert", // S_M_ADVANCED
        "Verlassen", // S_M_EXIT
        "T\175R MEN\175", // S_DOOR_MENU
        "\174ffnen als Gast 1", // S_OPEN_AS_G1
        "\174ffnen als Gast 2", // S_OPEN_AS_G2
        "\174ffnen als Admin", // S_OPEN_AS_ADMIN
        "Einst.", // S_SETTINGS
        "LOGIN EINST.", // S_LOGIN_SETTINGS
        "Login als Gast 1", // S_LOGIN_AS_G1
        "Login als Gast 2", // S_LOGIN_AS_G2
        "Login als Admin", // S_LOGIN_AS_ADMIN
        "Zur\200ck", // S_BACK
        "T\200r Entriegelt", // S_DOOR_UNLOCKED
        "Falsches Passwort", // S_INCORRECT_PASS
        "Passwort Gesp.!", // S_PASS_SAVED
        "Keine Benutzer", // S_MSG_NO_USERS
        "Keine weiteren", // S_MSG_USER_LIMIT_1
        "Benutzer", // S_MSG_USER_LIMIT_2
        "erlaubt.", // S_MSG_USER_LIMIT_3
        "ADMIN PROTOKOLL", // S_LOGS_TITLE
        "Keine Protokolle", // S_LOGS_NONE
        "Sprache W\176hlen", // S_LANG_SELECT
        "Anmeldeprotokoll", // S_M_LOGIN_SESSIONS
        "BENUTZER KONFIG", // S_CONF_TITLE
        "Aktiv:", // S_LBL_ACTIVE
        "PW \173nd:", // S_LBL_CHG_PW
        "Zug:", // S_ACC_TYPE
        "Anz:", // S_LBL_COUNT
        "Immer", // S_ACC_PERM
        "1-Mal", // S_ACC_ONCE
        "Multi", // S_ACC_MULTI
        "Weiter >", // S_NEXT
        "Speich.", // S_SAVE
        "Zugriff Abgel.", // S_ACCESS_DENIED
        "Verb:", // S_REMAINING
        "Login als User 1", // S_M_LOGIN_U1
        "Login als User 2", // S_M_LOGIN_U2
    }
};
