import re
import datetime
import os

def parse_po(filename):
    """Simple PO parser. Returns dict {msgid: msgstr} and list of ids in order."""
    data = {}
    order = []
    
    if not os.path.exists(filename):
        print(f"Error: {filename} not found.")
        return {}, []

    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Regex to find msgid "KEY" ... msgstr "VALUE"
    matches = re.findall(r'msgid\s+"([^"]+)"\s+msgstr\s+"([^"]+)"', content)
    
    for msgid, msgstr in matches:
        data[msgid] = msgstr
        order.append(msgid)
    return data, order

def encode_special_chars(text):
    replacements = {
        'Ä': '\\173', # 123
        'Ö': '\\174', # 124
        'Ü': '\\175', # 125
        'ä': '\\176', # 126
        'ö': '\\177', # 127
        'ü': '\\200', # 128
        'ß': '\\201', # 129
    }
    for char, code in replacements.items():
        text = text.replace(char, code)
    return text

def generate_c_files():
    en_data, en_order = parse_po('en.po')
    de_data, _ = parse_po('de.po')

    if not en_data:
        print("No data found in en.po. Aborting.")
        return

    # --- Header File (.h) ---
    h_content = f"""/* Generated by po2c.py on {datetime.datetime.now()} */
#ifndef LANGUAGES_H
#define LANGUAGES_H

#include <stdint.h>

// Global Language Setting
extern uint8_t sysLanguage; // 0=English, 1=German

// String Identifiers
enum StrID {{
"""
    for i, key in enumerate(en_order):
        h_content += f"    {key} = {i},\n"
    
    h_content += f"""    S_COUNT
}};

// String Table
extern const char* UI_STRINGS[2][S_COUNT];

// Helper Macro
#define GetStr(id) UI_STRINGS[sysLanguage][id]

#endif // LANGUAGES_H
"""

    with open('languages.h', 'w') as f:
        f.write(h_content)
    
    # --- Source File (.c) ---
    c_content = f"""/* Generated by po2c.py on {datetime.datetime.now()} */
#include "languages.h"

// --- DEFINITION OF GLOBAL VARIABLE ---
uint8_t sysLanguage = 0; // Default to English (0)

const char* UI_STRINGS[2][S_COUNT] = {{
    {{ // English
"""
    for key in en_order:
        text = en_data.get(key, "")
        c_content += f'        "{text}", // {key}\n'

    c_content += """    },
    { // German
"""
    for key in en_order:
        raw_text = de_data.get(key, en_data.get(key, "")) # Fallback to EN if missing
        encoded_text = encode_special_chars(raw_text)
        c_content += f'        "{encoded_text}", // {key}\n'

    c_content += """    }
};
"""

    with open('languages.c', 'w') as f:
        f.write(c_content)
    
    print("Generated languages.h and languages.c successfully.")

if __name__ == "__main__":
    generate_c_files()